### ISSUE TITLE
Jetty Stacktrace

### ISSUE THREAD

**Issue by wimjongman** [howlger/Eclipse-Help-Modernized#1]
I have been testing this. It looks fantastic. It is so much better. I love the search page.

When starting as instructed in Bug 501718 I noticed a stack trace. Could be unrelated but I have attached it here.

[stack.txt](https://github.com/howlger/Eclipse-Help-Modernized/files/5305878/stack.txt)

**Comment by howlger** [comment]
Glad you like it!

Thanks for the stack trace. It was indeed caused by the activation code for the UI that is part of the [Eclipse contribution: forwarding from inside a JSP to a non-JSP resource causes `java.lang.IllegalStateException: STREAM` to be thrown](https://git.eclipse.org/r/c/platform/eclipse.platform.ua/+/170090/1/org.eclipse.help.webapp/index.jsp#36). I have [updated the Eclipse patch to do it without forwarding to fix it](https://git.eclipse.org/r/c/platform/eclipse.platform.ua/+/170090/2/org.eclipse.help.webapp/index.jsp#44).
